use crate::cards::{Card, CardClass, CardData, CardType, Color, EquipmentSlot, Keyword, WeaponType};
use crate::card_effects::{AdditionalCostType, Ability, ConstantEffect, OnPlayConditionType, OnPlayEffect, OnPlayEffectType};
use std::sync::LazyLock;

/// Catalog of every card in the Rhinar vs Dorinthea classic battle.
///
/// The array is positional: index `i` corresponds to the `Card` enum variant
/// with discriminant `i` (see `cards::Card`). Data mirrors `classic_battles.py`.
///
/// Built exactly once on first access and shared thereafter, so hot paths that
/// look up card data don't re-materialize all 52 entries on every call.
static CARD_CATALOG: LazyLock<[CardData; 52]> = LazyLock::new(|| {
    [
        // ── HEROES ──────────────────────────────────────────────────────
        // Rhinar
        CardData {
            typ: CardType::Hero,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 20,
            hero_intellect: 4,
            // Constant ability: whenever Rhinar discards a card with 6 or more
            // power, Intimidate (the opponent banishes a card from hand). This
            // stacks with a card's own Intimidate keyword — e.g. Alpha Rampage
            // (Intimidate) that discards a 6-power card intimidates twice.
            constant_effect: Some(ConstantEffect::OnDiscard6Intimidate),
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Dorinthea, Quicksilver Prodigy
        CardData {
            typ: CardType::Hero,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 20,
            hero_intellect: 4,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // ── RHINAR — RED ────────────────────────────────────────────────
        // Alpha Rampage
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 3,
            pitch: 1,
            power: 9,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::RhinarSpecialization | Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            // "As an additional cost to play Alpha Rampage, discard a card."
            additional_cost: Some(AdditionalCostType::DiscardCard),
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Awakening Bellow
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::GoAgain | Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            // "The next attack action card you play this turn with the brute type
            // gains +3{p}." Unconditional on play; banks +3 for the next brute.
            play_effect: Some(OnPlayEffect {
                condition: OnPlayConditionType::Always,
                effectType: OnPlayEffectType::NextBrutePower,
                magnitude: 3,
            }),
        },
        // Bare Fangs
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 2,
            pitch: 1,
            power: 6,
            defense: 0,
            color: Some(Color::Red),
            no_block: true,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: Some(OnPlayEffect {
                condition: OnPlayConditionType::DrawDiscardHit6,
                effectType: OnPlayEffectType::ConditionalPower,
                magnitude: 2,
            }),
        },
        // Beast Mode
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 3,
            pitch: 1,
            power: 6,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            // "If you've intimidated this turn, this gets +2 power."
            play_effect: Some(OnPlayEffect {
                condition: OnPlayConditionType::HasIntimidated,
                effectType: OnPlayEffectType::ConditionalPower,
                magnitude: 2,
            }),
        },
        // Pack Hunt
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 2,
            pitch: 1,
            power: 6,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Wild Ride
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 2,
            pitch: 1,
            power: 6,
            defense: 0,
            color: Some(Color::Red),
            no_block: true,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            // Like Bare Fangs, draw then discard a card; if the discard had 6 or
            // more power the condition is met — but Wild Ride grants Go Again
            // rather than +power. Magnitude is unused for the Go Again effect.
            play_effect: Some(OnPlayEffect {
                condition: OnPlayConditionType::DrawDiscardHit6,
                effectType: OnPlayEffectType::ConditionalGoAgain,
                magnitude: 0,
            }),
        },
        // Wrecking Ball
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 3,
            pitch: 1,
            power: 6,
            defense: 0,
            color: Some(Color::Red),
            no_block: true,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            // "When you play Wrecking Ball, draw a card then discard a card. If
            // the discarded card has 6 or more power, Intimidate." Same draw-then-
            // discard condition as Bare Fangs / Wild Ride, but the payoff is an
            // Intimidate instead of a power/Go Again buff.
            play_effect: Some(OnPlayEffect {
                condition: OnPlayConditionType::DrawDiscardHit6,
                effectType: OnPlayEffectType::ConditionalIntimidate,
                magnitude: 0,
            }),
        },
        // ── RHINAR — YELLOW ─────────────────────────────────────────────
        // Barraging Beatdown
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 0,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::GoAgain | Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Muscle Mutt
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 2,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Pack Call
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Raging Onslaught
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Smash Instinct
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Smash with Big Tree
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 2,
            pitch: 2,
            power: 6,
            defense: 0,
            color: Some(Color::Yellow),
            no_block: true,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Wounded Bull
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 2,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            // "When you play Wounded Bull, if you have less health than an
            // opposing hero, it gains +1 power." The condition is checked as the
            // card resolves; the bonus is banked on the player and folded into
            // the chain's power when combat damage resolves.
            play_effect: Some(OnPlayEffect {
                condition: OnPlayConditionType::HasLessLife,
                effectType: OnPlayEffectType::ConditionalPower,
                magnitude: 1,
            }),
        },
        // ── RHINAR — BLUE ───────────────────────────────────────────────
        // Clearing Bellow
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::GoAgain | Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Come to Fight
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 1,
            pitch: 3,
            power: 0,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Dodge
        CardData {
            typ: CardType::DefenseReaction,
            weapon_type: None,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 2,
            color: Some(Color::Blue),
            no_block: true,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Rally the Rearguard
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 2,
            pitch: 3,
            power: 4,
            defense: 2,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: Some(Ability::DiscardCardPlusBlock),
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Titanium Bauble
        CardData {
            typ: CardType::Resource,
            weapon_type: None,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Wrecker Romp
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 2,
            pitch: 3,
            power: 6,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            // "As an additional cost to play Wrecker Romp, discard a card."
            additional_cost: Some(AdditionalCostType::DiscardCard),
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // ── RHINAR — MENTOR ─────────────────────────────────────────────
        // Chief Ruk'utan
        CardData {
            typ: CardType::Mentor,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // ── RHINAR — EQUIPMENT ──────────────────────────────────────────
        // Bone Basher
        CardData {
            typ: CardType::Weapon,
            weapon_type: Some(WeaponType::Club2h),
            cost: 2,
            pitch: 0,
            power: 4,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Weapon),
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: Some(Ability::Attack2),
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Blossom of Spring
        CardData {
            typ: CardType::Equipment,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Chest),
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: Some(Ability::DestroyGain1Resource),
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Bone Vizier
        CardData {
            typ: CardType::Equipment,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 1,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Head),
            card_class: CardClass::Brute,
            keyword: Keyword::BladeBreak,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Ironhide Gauntlet
        CardData {
            typ: CardType::Equipment,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Arms),
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Ironhide Legs
        CardData {
            typ: CardType::Equipment,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Legs),
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // ── DORINTHEA — RED ─────────────────────────────────────────────
        // En Garde
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Flock of the Feather Walkers
        CardData {
            typ: CardType::AttackAction,
            weapon_type: None,
            cost: 1,
            pitch: 1,
            power: 5,
            defense: 2,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // In the Swing
        CardData {
            typ: CardType::AttackReaction,
            weapon_type: None,
            cost: 0,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Ironsong Response
        CardData {
            typ: CardType::AttackReaction,
            weapon_type: None,
            cost: 0,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::Reprise,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Second Swing
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Sharpen Steel
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 0,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Thrust
        CardData {
            typ: CardType::AttackReaction,
            weapon_type: None,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 2,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Warrior's Valor
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // ── DORINTHEA — YELLOW ──────────────────────────────────────────
        // Driving Blade
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 2,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Glistening Steelblade
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 1,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::DorintheaSpecialization | Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // On a Knife Edge
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 0,
            pitch: 2,
            power: 0,
            defense: 2,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Out for Blood
        CardData {
            typ: CardType::AttackReaction,
            weapon_type: None,
            cost: 1,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Run Through
        CardData {
            typ: CardType::AttackReaction,
            weapon_type: None,
            cost: 1,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Slice and Dice
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 0,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // ── DORINTHEA — BLUE ────────────────────────────────────────────
        // Blade Flash
        CardData {
            typ: CardType::AttackReaction,
            weapon_type: None,
            cost: 1,
            pitch: 3,
            power: 0,
            defense: 2,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Hit and Run
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Sigil of Solace
        CardData {
            typ: CardType::Instant,
            weapon_type: None,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 0,
            color: Some(Color::Blue),
            no_block: true,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Toughen Up
        CardData {
            typ: CardType::DefenseReaction,
            weapon_type: None,
            cost: 2,
            pitch: 3,
            power: 0,
            defense: 4,
            color: Some(Color::Blue),
            no_block: true,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Visit the Blacksmith
        CardData {
            typ: CardType::Action,
            weapon_type: None,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 2,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // ── DORINTHEA — MENTOR ──────────────────────────────────────────
        // Hala Goldenhelm
        CardData {
            typ: CardType::Mentor,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 3,
            color: None,
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // ── DORINTHEA — EQUIPMENT ───────────────────────────────────────
        // Dawnblade, Resplendent
        CardData {
            typ: CardType::Weapon,
            weapon_type: Some(WeaponType::Sword2h),
            cost: 1,
            pitch: 0,
            power: 2,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Weapon),
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: Some(Ability::Attack1),
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Gallantry Gold
        CardData {
            typ: CardType::Equipment,
            weapon_type: None,
            cost: 1,
            pitch: 0,
            power: 0,
            defense: 1,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Arms),
            card_class: CardClass::Warrior,
            keyword: Keyword::Battleworn,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: Some(Ability::WeaponPlus1),
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Ironrot Helm
        CardData {
            typ: CardType::Equipment,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 1,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Head),
            card_class: CardClass::Generic,
            keyword: Keyword::BladeBreak,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
        // Ironrot Legs
        CardData {
            typ: CardType::Equipment,
            weapon_type: None,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 1,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Legs),
            card_class: CardClass::Generic,
            keyword: Keyword::BladeBreak,
            hero_life: 0,
            hero_intellect: 0,
            constant_effect: None,
            ability: None,
            defend_effect: None,
            next_attack_effect: None,
            additional_cost: None,
            target_effect: None,
            play_condition: None,
            play_effect: None,
        },
    ]
});

/// Returns a reference to the shared card catalog, initializing it on first use.
pub fn get_card_catalog() -> &'static [CardData; 52] {
    &CARD_CATALOG
}

impl Card {
    /// This card's static stats from the shared catalog. The catalog is
    /// positional — a `Card`'s discriminant is its index — so this is just that
    /// array index behind a name, letting call sites write `card.data()` instead
    /// of `get_card_catalog()[card as usize]` and dropping the `as usize` cast.
    pub fn data(self) -> &'static CardData {
        &get_card_catalog()[self as usize]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn two_handed_weapons_are_typed_weapon_with_a_weapon_type() {
        let bone_basher = Card::BoneBasher.data();
        assert_eq!(bone_basher.typ, CardType::Weapon);
        assert_eq!(bone_basher.weapon_type, Some(WeaponType::Club2h));

        let dawnblade = Card::Dawnblade.data();
        assert_eq!(dawnblade.typ, CardType::Weapon);
        assert_eq!(dawnblade.weapon_type, Some(WeaponType::Sword2h));
    }

    #[test]
    fn non_weapon_cards_have_no_weapon_type() {
        assert_eq!(Card::Rhinar.data().weapon_type, None);
        assert_eq!(Card::BoneVizier.data().weapon_type, None);
    }

    #[test]
    fn bare_fangs_has_draw_discard_hit6_conditional_power() {
        let effect = Card::BareFangsR
            .data()
            .play_effect
            .as_ref()
            .expect("Bare Fangs should carry an on-play effect");
        assert!(matches!(effect.condition, OnPlayConditionType::DrawDiscardHit6));
        assert!(matches!(effect.effectType, OnPlayEffectType::ConditionalPower));
        assert_eq!(effect.magnitude, 2);
    }
}
