use crate::cards::{CardClass, CardData, CardType, Color, EquipmentSlot, Keyword};

/// Catalog of every card in the Rhinar vs Dorinthea classic battle.
///
/// The array is positional: index `i` corresponds to the `Card` enum variant
/// with discriminant `i` (see `cards::Card`). Data mirrors `classic_battles.py`.
pub fn get_card_catalog() -> [CardData; 52] {
    [
        // ── HEROES ──────────────────────────────────────────────────────
        // Rhinar
        CardData {
            typ: CardType::Hero,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 20,
            hero_intellect: 4,
        },
        // Dorinthea, Quicksilver Prodigy
        CardData {
            typ: CardType::Hero,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 20,
            hero_intellect: 4,
        },
        // ── RHINAR — RED ────────────────────────────────────────────────
        // Alpha Rampage
        CardData {
            typ: CardType::AttackAction,
            cost: 3,
            pitch: 1,
            power: 9,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::RhinarSpecialization | Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Awakening Bellow
        CardData {
            typ: CardType::Action,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::GoAgain | Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Bare Fangs
        CardData {
            typ: CardType::AttackAction,
            cost: 2,
            pitch: 1,
            power: 6,
            defense: 0,
            color: Some(Color::Red),
            no_block: true,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Beast Mode
        CardData {
            typ: CardType::AttackAction,
            cost: 3,
            pitch: 1,
            power: 6,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Pack Hunt
        CardData {
            typ: CardType::AttackAction,
            cost: 2,
            pitch: 1,
            power: 6,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Wild Ride
        CardData {
            typ: CardType::AttackAction,
            cost: 2,
            pitch: 1,
            power: 6,
            defense: 0,
            color: Some(Color::Red),
            no_block: true,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Wrecking Ball
        CardData {
            typ: CardType::AttackAction,
            cost: 3,
            pitch: 1,
            power: 6,
            defense: 0,
            color: Some(Color::Red),
            no_block: true,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // ── RHINAR — YELLOW ─────────────────────────────────────────────
        // Barraging Beatdown
        CardData {
            typ: CardType::Action,
            cost: 0,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::GoAgain | Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Muscle Mutt
        CardData {
            typ: CardType::AttackAction,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 2,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Pack Call
        CardData {
            typ: CardType::AttackAction,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Raging Onslaught
        CardData {
            typ: CardType::AttackAction,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Smash Instinct
        CardData {
            typ: CardType::AttackAction,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Smash with Big Tree
        CardData {
            typ: CardType::AttackAction,
            cost: 2,
            pitch: 2,
            power: 6,
            defense: 0,
            color: Some(Color::Yellow),
            no_block: true,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Wounded Bull
        CardData {
            typ: CardType::AttackAction,
            cost: 3,
            pitch: 2,
            power: 6,
            defense: 2,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // ── RHINAR — BLUE ───────────────────────────────────────────────
        // Clearing Bellow
        CardData {
            typ: CardType::Action,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::GoAgain | Keyword::Intimidate,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Come to Fight
        CardData {
            typ: CardType::Action,
            cost: 1,
            pitch: 3,
            power: 0,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Dodge
        CardData {
            typ: CardType::DefenseReaction,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 2,
            color: Some(Color::Blue),
            no_block: true,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Rally the Rearguard
        CardData {
            typ: CardType::AttackAction,
            cost: 2,
            pitch: 3,
            power: 4,
            defense: 2,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Titanium Bauble
        CardData {
            typ: CardType::Resource,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Wrecker Romp
        CardData {
            typ: CardType::AttackAction,
            cost: 2,
            pitch: 3,
            power: 6,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // ── RHINAR — MENTOR ─────────────────────────────────────────────
        // Chief Ruk'utan
        CardData {
            typ: CardType::Mentor,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: None,
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // ── RHINAR — EQUIPMENT ──────────────────────────────────────────
        // Bone Basher
        CardData {
            typ: CardType::Club2h,
            cost: 2,
            pitch: 0,
            power: 4,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Weapon),
            card_class: CardClass::Brute,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Blossom of Spring
        CardData {
            typ: CardType::Equipment,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Chest),
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Bone Vizier
        CardData {
            typ: CardType::Equipment,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 1,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Head),
            card_class: CardClass::Brute,
            keyword: Keyword::BladeBreak,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Ironhide Gauntlet
        CardData {
            typ: CardType::Equipment,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Arms),
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Ironhide Legs
        CardData {
            typ: CardType::Equipment,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Legs),
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // ── DORINTHEA — RED ─────────────────────────────────────────────
        // En Garde
        CardData {
            typ: CardType::Action,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Flock of the Feather Walkers
        CardData {
            typ: CardType::AttackAction,
            cost: 1,
            pitch: 1,
            power: 5,
            defense: 2,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // In the Swing
        CardData {
            typ: CardType::AttackReaction,
            cost: 0,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Ironsong Response
        CardData {
            typ: CardType::AttackReaction,
            cost: 0,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::Reprise,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Second Swing
        CardData {
            typ: CardType::Action,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Sharpen Steel
        CardData {
            typ: CardType::Action,
            cost: 0,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Thrust
        CardData {
            typ: CardType::AttackReaction,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 2,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Warrior's Valor
        CardData {
            typ: CardType::Action,
            cost: 1,
            pitch: 1,
            power: 0,
            defense: 3,
            color: Some(Color::Red),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // ── DORINTHEA — YELLOW ──────────────────────────────────────────
        // Driving Blade
        CardData {
            typ: CardType::Action,
            cost: 2,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Glistening Steelblade
        CardData {
            typ: CardType::Action,
            cost: 1,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::DorintheaSpecialization | Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // On a Knife Edge
        CardData {
            typ: CardType::Action,
            cost: 0,
            pitch: 2,
            power: 0,
            defense: 2,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Out for Blood
        CardData {
            typ: CardType::AttackReaction,
            cost: 1,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Run Through
        CardData {
            typ: CardType::AttackReaction,
            cost: 1,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Slice and Dice
        CardData {
            typ: CardType::Action,
            cost: 0,
            pitch: 2,
            power: 0,
            defense: 3,
            color: Some(Color::Yellow),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // ── DORINTHEA — BLUE ────────────────────────────────────────────
        // Blade Flash
        CardData {
            typ: CardType::AttackReaction,
            cost: 1,
            pitch: 3,
            power: 0,
            defense: 2,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Hit and Run
        CardData {
            typ: CardType::Action,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 3,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Sigil of Solace
        CardData {
            typ: CardType::Instant,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 0,
            color: Some(Color::Blue),
            no_block: true,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Toughen Up
        CardData {
            typ: CardType::DefenseReaction,
            cost: 2,
            pitch: 3,
            power: 0,
            defense: 4,
            color: Some(Color::Blue),
            no_block: true,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Visit the Blacksmith
        CardData {
            typ: CardType::Action,
            cost: 0,
            pitch: 3,
            power: 0,
            defense: 2,
            color: Some(Color::Blue),
            no_block: false,
            slot: None,
            card_class: CardClass::Generic,
            keyword: Keyword::GoAgain,
            hero_life: 0,
            hero_intellect: 0,
        },
        // ── DORINTHEA — MENTOR ──────────────────────────────────────────
        // Hala Goldenhelm
        CardData {
            typ: CardType::Mentor,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 3,
            color: None,
            no_block: false,
            slot: None,
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // ── DORINTHEA — EQUIPMENT ───────────────────────────────────────
        // Dawnblade, Resplendent
        CardData {
            typ: CardType::Sword2h,
            cost: 1,
            pitch: 0,
            power: 2,
            defense: 0,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Weapon),
            card_class: CardClass::Warrior,
            keyword: Keyword::empty(),
            hero_life: 0,
            hero_intellect: 0,
        },
        // Gallantry Gold
        CardData {
            typ: CardType::Equipment,
            cost: 1,
            pitch: 0,
            power: 0,
            defense: 1,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Arms),
            card_class: CardClass::Warrior,
            keyword: Keyword::Battleworn,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Ironrot Helm
        CardData {
            typ: CardType::Equipment,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 1,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Head),
            card_class: CardClass::Generic,
            keyword: Keyword::BladeBreak,
            hero_life: 0,
            hero_intellect: 0,
        },
        // Ironrot Legs
        CardData {
            typ: CardType::Equipment,
            cost: 0,
            pitch: 0,
            power: 0,
            defense: 1,
            color: None,
            no_block: false,
            slot: Some(EquipmentSlot::Legs),
            card_class: CardClass::Generic,
            keyword: Keyword::BladeBreak,
            hero_life: 0,
            hero_intellect: 0,
        },
    ]
}
